import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { connectWallet } from '../components/web3connect'
import { useRouter } from 'next/router';
import { Space } from 'antd';



export default function Home() {

  const router = useRouter();
  

  async function verifyUser() {
    const output = await connectWallet()
    if (output === 0) {
      router.push('/denied')
    }
    else {
      router.push('/create')
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Verify Creator Portal</title>
        <meta name="Mint an NFT to access Our Creator portal!" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <h1 className={styles.title} style={{marginBottom: "1em"}}>
  Connect to NFT Creator Portal 
  <button style={{fontSize:'25px', color: "black", borderRadius: "10px"}} onClick={verifyUser}>
    CONNECT WALLET
  </button>
</h1>
       
<p className={styles.grid} style={{marginBottom: "1em"}}>
  Get ready to unleash your creativity and bring your artistic vision to life! This is the gateway to our NFT Creation Portal, where you can craft your own unique NFTs with ease. With just a few clicks, you will be able to turn your artwork into one-of-a-kind digital treasures. So why wait? Step right up and start creating your NFT masterpieces today!
</p>
<p className={styles.grid}>
To access the NFT Creation Portal, it is required that you possess at least one Astro Alien in your wallet. You may access the portal once you have an Astro Alien in your wallet, Verify your ownership by clicking the Connect Wallet button. If no Astro Alien is found in your wallet upon clicking Connect Wallet, access will be denied. <strong>You MUST be connected to Songbird Network when clicking Connect Wallet</strong></p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Songbird Astro Aliens Mint Dapp &rarr;</h2>
            <img src="Aliens.gif" alt="Alien Monsters" width="250" height="300" style={{borderRadius: '10%'}} />


            <p>
             Mint a Songbird Astro Alien!
            </p>
          </a>

         <a href="https://www.monstersnftinc.co/monsters/" className={styles.card}>
         <h2>Flare Marvelous Monsters Mint Dapp &rarr;</h2>
         <img src="Monsters.gif" alt="Flare Marvelous Monsters" width="250" height="275" style={{borderRadius: '10%'}}/>
  
  <p>Mint a Flare Networks Marvelous Monster!</p>
</a>


          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Unleash an abundance of possibilities with massive collections! &rarr;</h2>
            <img src="MonsterDaddy_dr_suess_trippy_wall_paper_world_with_cute_and_ado_7f07fe86-3fb5-4b93-acda-349c66a2d77b.png" alt="Monsters" width="400" height="400"  style={{borderRadius: '10%' }}/>

            <p>Looking to establish a substantial NFT collection? Monsters NFT Inc. has the perfect solution for you! Our development and art teams specialize in assisting with the creation of NFT collections of all sizes, from 0 to 20,000+ NFTs. Our services include the production of high quality art, the creation of metadata, uploading to IPFS, writing smart contracts, developing web3 dapps, and front-end design. </p>
          </a>

          <a
            href="https://www.monstersnftinc.co/sgb-monster-dudes/"
            className={styles.card}
            style={{ width: '400px', height: '1000px' }}
          >
            <h2> Songbird Monster Dudes &rarr;</h2>
            <img src="example.gif" alt="Monsters" width="400" height="400"  style={{borderRadius: '10%' }}/>

            <p>
              Mint your Songbird Monster Dudes here! This was our first collection released on Songbird Network! Its the Cheapest and largest collection ever made on Songbird!
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
